{
 "bad": [
  "GeomFill_NSections",
  "OCC.Core.Adaptor2d.Adaptor2d_Curve2d",
  "OCC.Core.Adaptor2d.Adaptor2d_HCurve2d",
  "OCC.Core.Adaptor3d.Adaptor3d_Curve",
  "OCC.Core.Adaptor3d.Adaptor3d_HCurve",
  "OCC.Core.Adaptor3d.Adaptor3d_HSurface",
  "OCC.Core.Adaptor3d.Adaptor3d_Surface",
  "OCC.Core.Approx.Approx_Curve3d",
  "OCC.Core.Approx.Approx_CurvilinearParameter",
  "OCC.Core.BRep.BRep_Builder",
  "OCC.Core.BRep.BRep_Tool",
  "OCC.Core.BRep.BRep_Tool.Curve",
  "OCC.Core.BRep.BRep_Tool.Pnt",
  "OCC.Core.BRep.BRep_Tool.Surface",
  "OCC.Core.BRepAdaptor.BRepAdaptor_CompCurve",
  "OCC.Core.BRepAdaptor.BRepAdaptor_Curve",
  "OCC.Core.BRepAdaptor.BRepAdaptor_HCompCurve",
  "OCC.Core.BRepAdaptor.BRepAdaptor_HCurve",
  "OCC.Core.BRepAdaptor.BRepAdaptor_Surface",
  "OCC.Core.BRepAlgoAPI.BRepAlgoAPI_Common",
  "OCC.Core.BRepAlgoAPI.BRepAlgoAPI_Cut",
  "OCC.Core.BRepAlgoAPI.BRepAlgoAPI_Fuse",
  "OCC.Core.BRepAlgoAPI.BRepAlgoAPI_Section",
  "OCC.Core.BRepAlgoAPI.BRepAlgoAPI_Splitter",
  "OCC.Core.BRepBndLib.brepbndlib",
  "OCC.Core.BRepBndLib.brepbndlib.Add",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeEdge",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeFace",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakePolygon",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeShell",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeSolid",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeVertex",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeWire",
  "OCC.Core.BRepBuilderAPI.BRepBuilderAPI_Sewing",
  "OCC.Core.BRepExtrema.BRepExtrema_DistShapeShape",
  "OCC.Core.BRepFilletAPI.BRepFilletAPI_MakeFillet",
  "OCC.Core.BRepGProp.brepgprop",
  "OCC.Core.BRepGProp.brepgprop.SurfaceProperties",
  "OCC.Core.BRepGProp.brepgprop.VolumeProperties",
  "OCC.Core.BRepMesh.BRepMesh_IncrementalMesh",
  "OCC.Core.BRepOffsetAPI.BRepOffsetAPI_MakeOffset",
  "OCC.Core.BRepOffsetAPI.BRepOffsetAPI_MakePipe",
  "OCC.Core.BRepOffsetAPI.BRepOffsetAPI_MakePipeShell",
  "OCC.Core.BRepOffsetAPI.BRepOffsetAPI_ThruSections",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeBox",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeCone",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeHalfSpace",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakePrism",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeRevol",
  "OCC.Core.BRepPrimAPI.BRepPrimAPI_MakeSphere",
  "OCC.Core.Bnd.Bnd_Box",
  "OCC.Core.Extrema.Extrema_ExtCC",
  "OCC.Core.Extrema.Extrema_ExtCC2d",
  "OCC.Core.Extrema.Extrema_ExtCS",
  "OCC.Core.Extrema.Extrema_ExtPC",
  "OCC.Core.Extrema.Extrema_ExtPC2d",
  "OCC.Core.Extrema.Extrema_ExtPS",
  "OCC.Core.Extrema.Extrema_POnCurv",
  "OCC.Core.Extrema.Extrema_POnCurv2d",
  "OCC.Core.Extrema.Extrema_POnSurf",
  "OCC.Core.GC.GC_MakeArcOfCircle",
  "OCC.Core.GC.GC_MakeArcOfEllipse",
  "OCC.Core.GC.GC_MakeCircle",
  "OCC.Core.GC.GC_MakeEllipse",
  "OCC.Core.GC.GC_MakeLine",
  "OCC.Core.GC.GC_MakeSegment",
  "OCC.Core.GCE2d.GCE2d_MakeArcOfCircle",
  "OCC.Core.GCE2d.GCE2d_MakeCircle",
  "OCC.Core.GCE2d.GCE2d_MakeLine",
  "OCC.Core.GCE2d.GCE2d_MakeSegment",
  "OCC.Core.GCPnts.GCPnts_AbscissaPoint",
  "OCC.Core.GCPnts.GCPnts_TangentialDeflection",
  "OCC.Core.GProp.GProp_GProps",
  "OCC.Core.GccEnt.GccEnt_unqualified",
  "OCC.Core.Geom.Geom_BSplineCurve",
  "OCC.Core.Geom.Geom_BSplineSurface",
  "OCC.Core.Geom.Geom_BezierCurve",
  "OCC.Core.Geom.Geom_BezierCurve.DownCast",
  "OCC.Core.Geom.Geom_BezierSurface",
  "OCC.Core.Geom.Geom_Circle",
  "OCC.Core.Geom.Geom_Circle.DownCast",
  "OCC.Core.Geom.Geom_Curve",
  "OCC.Core.Geom.Geom_Curve.DownCast",
  "OCC.Core.Geom.Geom_Ellipse",
  "OCC.Core.Geom.Geom_Geometry",
  "OCC.Core.Geom.Geom_Line",
  "OCC.Core.Geom.Geom_OffsetCurve",
  "OCC.Core.Geom.Geom_Plane",
  "OCC.Core.Geom.Geom_RectangularTrimmedSurface",
  "OCC.Core.Geom.Geom_Surface",
  "OCC.Core.Geom.Geom_SurfaceOfLinearExtrusion",
  "OCC.Core.Geom.Geom_SurfaceOfRevolution",
  "OCC.Core.Geom.Geom_TrimmedCurve",
  "OCC.Core.Geom2d.Geom2d_BSplineCurve",
  "OCC.Core.Geom2d.Geom2d_BSplineCurve.DownCast",
  "OCC.Core.Geom2d.Geom2d_BezierCurve",
  "OCC.Core.Geom2d.Geom2d_BezierCurve.DownCast",
  "OCC.Core.Geom2d.Geom2d_CartesianPoint",
  "OCC.Core.Geom2d.Geom2d_Circle",
  "OCC.Core.Geom2d.Geom2d_Circle.DownCast",
  "OCC.Core.Geom2d.Geom2d_Curve",
  "OCC.Core.Geom2d.Geom2d_Curve.DownCast",
  "OCC.Core.Geom2d.Geom2d_Ellipse",
  "OCC.Core.Geom2d.Geom2d_Geometry",
  "OCC.Core.Geom2d.Geom2d_Line",
  "OCC.Core.Geom2d.Geom2d_Point",
  "OCC.Core.Geom2d.Geom2d_TrimmedCurve",
  "OCC.Core.Geom2dAPI.Geom2dAPI_Interpolate",
  "OCC.Core.Geom2dAPI.Geom2dAPI_PointsToBSpline",
  "OCC.Core.Geom2dAPI.Geom2dAPI_ProjectPointOnCurve",
  "OCC.Core.Geom2dAdaptor.Geom2dAdaptor_Curve",
  "OCC.Core.Geom2dAdaptor.Geom2dAdaptor_HCurve",
  "OCC.Core.Geom2dGcc.Geom2dGcc_Circ2d2TanOn",
  "OCC.Core.Geom2dGcc.Geom2dGcc_Circ2d2TanRad",
  "OCC.Core.Geom2dGcc.Geom2dGcc_Circ2d3Tan",
  "OCC.Core.Geom2dGcc.Geom2dGcc_Circ2dTanCen",
  "OCC.Core.Geom2dGcc.Geom2dGcc_QualifiedCurve",
  "OCC.Core.Geom2dLProp.Geom2dLProp_CLProps2d",
  "OCC.Core.GeomAPI.GeomAPI_Interpolate",
  "OCC.Core.GeomAPI.GeomAPI_PointsToBSpline",
  "OCC.Core.GeomAPI.GeomAPI_ProjectPointOnCurve",
  "OCC.Core.GeomAPI.GeomAPI_ProjectPointOnSurf",
  "OCC.Core.GeomAPI.geomapi",
  "OCC.Core.GeomAPI.geomapi.To2d",
  "OCC.Core.GeomAPI.geomapi.To3d",
  "OCC.Core.GeomAbs.GeomAbs_Arc",
  "OCC.Core.GeomAbs.GeomAbs_C0",
  "OCC.Core.GeomAbs.GeomAbs_C1",
  "OCC.Core.GeomAbs.GeomAbs_C2",
  "OCC.Core.GeomAbs.GeomAbs_CN",
  "OCC.Core.GeomAdaptor.GeomAdaptor_Curve",
  "OCC.Core.GeomAdaptor.GeomAdaptor_HCurve",
  "OCC.Core.GeomAdaptor.GeomAdaptor_Surface",
  "OCC.Core.IGESControl.IGESControl_Controller",
  "OCC.Core.IGESControl.IGESControl_Writer",
  "OCC.Core.LProp3d.LProp3d_CLProps",
  "OCC.Core.Law.Law_Interpol",
  "OCC.Core.Precision.precision",
  "OCC.Core.Precision.precision.Approximation",
  "OCC.Core.Precision.precision.Confusion",
  "OCC.Core.Precision.precision.Infinite",
  "OCC.Core.Precision.precision.IsInfinite",
  "OCC.Core.ProjLib.projlib",
  "OCC.Core.ProjLib.projlib.Project",
  "OCC.Core.STEPControl.STEPControl_AsIs",
  "OCC.Core.STEPControl.STEPControl_Writer",
  "OCC.Core.ShapeAnalysis.ShapeAnalysis_Edge",
  "OCC.Core.ShapeFix.ShapeFix_ShapeTolerance",
  "OCC.Core.ShapeUpgrade.ShapeUpgrade_ShapeDivideContinuity",
  "OCC.Core.TColGeom.TColGeom_SequenceOfCurve",
  "OCC.Core.TColStd.TColStd_Array1OfBoolean",
  "OCC.Core.TColStd.TColStd_Array1OfInteger",
  "OCC.Core.TColStd.TColStd_Array1OfReal",
  "OCC.Core.TColStd.TColStd_Array2OfBoolean",
  "OCC.Core.TColStd.TColStd_Array2OfInteger",
  "OCC.Core.TColStd.TColStd_Array2OfReal",
  "OCC.Core.TColStd.TColStd_HArray1OfBoolean",
  "OCC.Core.TColStd.TColStd_HArray1OfInteger",
  "OCC.Core.TColStd.TColStd_HArray1OfReal",
  "OCC.Core.TColgp.TColgp_Array1OfPnt",
  "OCC.Core.TColgp.TColgp_Array1OfPnt2d",
  "OCC.Core.TColgp.TColgp_Array1OfVec",
  "OCC.Core.TColgp.TColgp_Array1OfVec2d",
  "OCC.Core.TColgp.TColgp_Array2OfPnt",
  "OCC.Core.TColgp.TColgp_Array2OfPnt2d",
  "OCC.Core.TColgp.TColgp_HArray1OfPnt",
  "OCC.Core.TColgp.TColgp_HArray1OfPnt2d",
  "OCC.Core.TColgp.TColgp_HArray1OfVec",
  "OCC.Core.TColgp.TColgp_HArray1OfVec2d",
  "OCC.Core.TColgp.TColgp_HArray2OfPnt",
  "OCC.Core.TColgp.TColgp_HArray2OfPnt2d",
  "OCC.Core.TopAbs.TopAbs_COMPOUND",
  "OCC.Core.TopAbs.TopAbs_COMPSOLID",
  "OCC.Core.TopAbs.TopAbs_EDGE",
  "OCC.Core.TopAbs.TopAbs_FACE",
  "OCC.Core.TopAbs.TopAbs_SHELL",
  "OCC.Core.TopAbs.TopAbs_SOLID",
  "OCC.Core.TopAbs.TopAbs_VERTEX",
  "OCC.Core.TopAbs.TopAbs_WIRE",
  "OCC.Core.TopExp.topexp",
  "OCC.Core.TopExp.topexp.MapShapes",
  "OCC.Core.TopLoc.TopLoc_Location",
  "OCC.Core.TopTools.TopTools_IndexedMapOfShape",
  "OCC.Core.TopTools.TopTools_ListIteratorOfListOfShape",
  "OCC.Core.TopTools.TopTools_ListOfShape",
  "OCC.Core.TopoDS.TopoDS_CompSolid",
  "OCC.Core.TopoDS.TopoDS_Compound",
  "OCC.Core.TopoDS.TopoDS_Edge",
  "OCC.Core.TopoDS.TopoDS_Face",
  "OCC.Core.TopoDS.TopoDS_Shape",
  "OCC.Core.TopoDS.TopoDS_Shell",
  "OCC.Core.TopoDS.TopoDS_Solid",
  "OCC.Core.TopoDS.TopoDS_Vertex",
  "OCC.Core.TopoDS.TopoDS_Wire",
  "OCC.Core.TopoDS.topods",
  "OCC.Core.TopoDS.topods.CompSolid",
  "OCC.Core.TopoDS.topods.Compound",
  "OCC.Core.TopoDS.topods.Edge",
  "OCC.Core.TopoDS.topods.Face",
  "OCC.Core.TopoDS.topods.Shell",
  "OCC.Core.TopoDS.topods.Solid",
  "OCC.Core.TopoDS.topods.Vertex",
  "OCC.Core.TopoDS.topods.Wire",
  "OCC.Core.TopoDS.topods_CompSolid",
  "OCC.Core.TopoDS.topods_Compound",
  "OCC.Core.TopoDS.topods_Edge",
  "OCC.Core.TopoDS.topods_Face",
  "OCC.Core.TopoDS.topods_Shell",
  "OCC.Core.TopoDS.topods_Solid",
  "OCC.Core.TopoDS.topods_Vertex",
  "OCC.Core.TopoDS.topods_Wire",
  "OCC.Core.gp.gp_Ax1",
  "OCC.Core.gp.gp_Ax2",
  "OCC.Core.gp.gp_Ax22d",
  "OCC.Core.gp.gp_Ax2d",
  "OCC.Core.gp.gp_Ax3",
  "OCC.Core.gp.gp_Circ",
  "OCC.Core.gp.gp_Circ2d",
  "OCC.Core.gp.gp_Dir",
  "OCC.Core.gp.gp_Dir2d",
  "OCC.Core.gp.gp_Elips",
  "OCC.Core.gp.gp_Lin",
  "OCC.Core.gp.gp_Lin2d",
  "OCC.Core.gp.gp_Pln",
  "OCC.Core.gp.gp_Pnt",
  "OCC.Core.gp.gp_Pnt2d",
  "OCC.Core.gp.gp_Quaternion",
  "OCC.Core.gp.gp_Trsf",
  "OCC.Core.gp.gp_Trsf2d",
  "OCC.Core.gp.gp_Vec",
  "OCC.Core.gp.gp_Vec2d",
  "OCC.Core.gp.gp_XY",
  "OCC.Core.gp.gp_XYZ",
  "TestClass",
  "_add_element_to_list",
  "collections.abc.Iterable",
  "create_common",
  "get_ax",
  "move_point_and_tangent",
  "numpy.float32",
  "numpy.radians",
  "numpy.uint16",
  "numpy.uint32",
  "os.path.dirname",
  "os.path.exists",
  "os.path.join",
  "os.path.relpath",
  "os.path.splitext",
  "os.remove",
  "os.sep.join",
  "pyoccad.__file__",
  "pyoccad.__name__",
  "pyoccad.create.CreateArc.from_angles",
  "pyoccad.create.CreateArray1.of_floats",
  "pyoccad.create.CreateArray1.of_points",
  "pyoccad.create.CreateArray1.of_vectors",
  "pyoccad.create.CreateAxis.as_axis",
  "pyoccad.create.CreateAxis.from_location_and_direction",
  "pyoccad.create.CreateAxis.ox",
  "pyoccad.create.CreateAxis.oy",
  "pyoccad.create.CreateAxis.oz",
  "pyoccad.create.CreateBSpline.approximation",
  "pyoccad.create.CreateBSpline.from_points",
  "pyoccad.create.CreateBSpline.from_points_and_tangents_interpolate",
  "pyoccad.create.CreateBSpline.from_points_interpolate",
  "pyoccad.create.CreateBSpline.from_points_interpolate_with_bounds_control",
  "pyoccad.create.CreateBSpline.from_points_with_params",
  "pyoccad.create.CreateBSpline.from_points_with_smoothing",
  "pyoccad.create.CreateBSpline.from_poles_and_degree",
  "pyoccad.create.CreateBezier.c1_connecting_curves",
  "pyoccad.create.CreateBezier.c1_connecting_curves_end_start",
  "pyoccad.create.CreateBezier.c1_continuity",
  "pyoccad.create.CreateBezier.connecting_curves",
  "pyoccad.create.CreateBezier.from_control_points",
  "pyoccad.create.CreateBezier.from_poles",
  "pyoccad.create.CreateBezier.g1_absolute_tension",
  "pyoccad.create.CreateBezier.g1_relative_tension",
  "pyoccad.create.CreateBezier.tangent_c0_continuity",
  "pyoccad.create.CreateBezierSurface.from_poles",
  "pyoccad.create.CreateBox.bounding_box",
  "pyoccad.create.CreateBox.from_dimensions",
  "pyoccad.create.CreateBox.from_dimensions_and_center",
  "pyoccad.create.CreateCircle._CreateCircle__get_extrema",
  "pyoccad.create.CreateCircle.bi_tangent_with_position",
  "pyoccad.create.CreateCircle.bi_tangent_with_radius",
  "pyoccad.create.CreateCircle.from_2d",
  "pyoccad.create.CreateCircle.from_3_points",
  "pyoccad.create.CreateCircle.from_3d",
  "pyoccad.create.CreateCircle.from_radius_and_axis",
  "pyoccad.create.CreateCircle.from_radius_and_center",
  "pyoccad.create.CreateCircle.tangent_and_center",
  "pyoccad.create.CreateCircle.tri_tangent",
  "pyoccad.create.CreateCone.from_base_and_dir",
  "pyoccad.create.CreateControlPoint.from_point",
  "pyoccad.create.CreateCoordSystem.as_coord_system",
  "pyoccad.create.CreateCoordSystem.from_location_and_directions",
  "pyoccad.create.CreateCoordSystem.ox",
  "pyoccad.create.CreateCoordSystem.oy",
  "pyoccad.create.CreateCoordSystem.oz",
  "pyoccad.create.CreateCoordSystem.rotated_ox",
  "pyoccad.create.CreateCoordSystem.rotated_oy",
  "pyoccad.create.CreateCoordSystem.rotated_oz",
  "pyoccad.create.CreateCurve.as_adaptor",
  "pyoccad.create.CreateCurve.as_adaptor_handler",
  "pyoccad.create.CreateCurve.as_curve",
  "pyoccad.create.CreateCurve.curvilinear_trimmed",
  "pyoccad.create.CreateCurve.from_2d",
  "pyoccad.create.CreateCurve.from_3d",
  "pyoccad.create.CreateCurve.from_adaptor",
  "pyoccad.create.CreateCurve.from_edge",
  "pyoccad.create.CreateCurve.trimmed",
  "pyoccad.create.CreateDirection.as_direction",
  "pyoccad.create.CreateEdge.as_edge",
  "pyoccad.create.CreateEdge.from_2_points",
  "pyoccad.create.CreateEdge.from_adaptor",
  "pyoccad.create.CreateEdge.from_contour",
  "pyoccad.create.CreateEdge.from_curve",
  "pyoccad.create.CreateExtrusion.curve",
  "pyoccad.create.CreateExtrusion.surface",
  "pyoccad.create.CreateFace.from_contour",
  "pyoccad.create.CreateFace.from_plane_and_shape_sizes",
  "pyoccad.create.CreateFace.from_plane_and_sizes",
  "pyoccad.create.CreateFace.from_points",
  "pyoccad.create.CreateHArray1.of_points",
  "pyoccad.create.CreateInterpolation.of_points",
  "pyoccad.create.CreateIntersection.between_2_curves",
  "pyoccad.create.CreateIntersection.between_curve_and_surface",
  "pyoccad.create.CreateIntersection.between_point_and_curve",
  "pyoccad.create.CreateIntersection.between_point_and_surface",
  "pyoccad.create.CreateLine.between_2_curves_at_positions",
  "pyoccad.create.CreateLine.between_2_curves_ends",
  "pyoccad.create.CreateLine.between_2_curves_starts",
  "pyoccad.create.CreateLine.between_2_points",
  "pyoccad.create.CreateLine.from_point_and_direction",
  "pyoccad.create.CreateLine.normal_to_curve",
  "pyoccad.create.CreateList.from_occ_list",
  "pyoccad.create.CreateOCCList.of_shapes",
  "pyoccad.create.CreateOffset.face_from_curve",
  "pyoccad.create.CreateOffset.wire_from_curve",
  "pyoccad.create.CreatePlane.from_axis",
  "pyoccad.create.CreatePlane.normal_to_curve_at_position",
  "pyoccad.create.CreatePlane.xoy",
  "pyoccad.create.CreatePlane.xpy",
  "pyoccad.create.CreatePlane.yoz",
  "pyoccad.create.CreatePoint.as_list",
  "pyoccad.create.CreatePoint.as_ndarray",
  "pyoccad.create.CreatePoint.as_point",
  "pyoccad.create.CreatePoint.as_point_in_referential",
  "pyoccad.create.CreatePoint.as_tuple",
  "pyoccad.create.CreatePoint.barycenter",
  "pyoccad.create.CreatePoint.centroid",
  "pyoccad.create.CreatePoint.from_curve",
  "pyoccad.create.CreatePoint.from_curve_relative_pos",
  "pyoccad.create.CreatePoint.from_cylindrical",
  "pyoccad.create.CreatePoint.from_vertex",
  "pyoccad.create.CreatePoint.projected_on_plane",
  "pyoccad.create.CreateRevolution.solid_from_curve",
  "pyoccad.create.CreateRevolution.solid_from_face",
  "pyoccad.create.CreateRevolution.surface_from_curve",
  "pyoccad.create.CreateRevolution.trimmed_surface_from_curve",
  "pyoccad.create.CreateRotation.rotation_x",
  "pyoccad.create.CreateRotation.rotation_x_deg",
  "pyoccad.create.CreateRotation.rotation_y",
  "pyoccad.create.CreateRotation.rotation_y_deg",
  "pyoccad.create.CreateRotation.rotation_z",
  "pyoccad.create.CreateRotation.rotation_z_deg",
  "pyoccad.create.CreateScaling.from_2d_scale_factor",
  "pyoccad.create.CreateScaling.from_factor",
  "pyoccad.create.CreateScaling.from_factor_and_center",
  "pyoccad.create.CreateSequence.of_curves",
  "pyoccad.create.CreateShell.from_faces",
  "pyoccad.create.CreateSolid.from_shell",
  "pyoccad.create.CreateSphere.from_radius_and_center",
  "pyoccad.create.CreateSurface.as_adaptor",
  "pyoccad.create.CreateSymmetry.from_ox_axis",
  "pyoccad.create.CreateSymmetry.from_oy_axis",
  "pyoccad.create.CreateSymmetry.from_oz_axis",
  "pyoccad.create.CreateTopology.as_shape",
  "pyoccad.create.CreateTopology.make_compound",
  "pyoccad.create.CreateTopology.make_compsolid",
  "pyoccad.create.CreateTopology.make_edge",
  "pyoccad.create.CreateTopology.make_face",
  "pyoccad.create.CreateTopology.make_shell",
  "pyoccad.create.CreateTopology.make_solid",
  "pyoccad.create.CreateTopology.make_vertex",
  "pyoccad.create.CreateTopology.make_wire",
  "pyoccad.create.CreateTranslation.from_vector",
  "pyoccad.create.CreateUnsignedCoordSystem.as_coord_system",
  "pyoccad.create.CreateUnsignedCoordSystem.from_location_and_directions",
  "pyoccad.create.CreateUnsignedCoordSystem.ox",
  "pyoccad.create.CreateUnsignedCoordSystem.oy",
  "pyoccad.create.CreateUnsignedCoordSystem.oz",
  "pyoccad.create.CreateVector.as_list",
  "pyoccad.create.CreateVector.as_vector",
  "pyoccad.create.CreateVector.from_2_points",
  "pyoccad.create.CreateVector.from_point",
  "pyoccad.create.CreateVertex.from_point",
  "pyoccad.create.CreateWire.from_element",
  "pyoccad.create.CreateWire.from_elements",
  "pyoccad.create.CreateWire.from_plane_and_sizes",
  "pyoccad.create.CreateWire.from_points",
  "pyoccad.explore.ExploreSubshapes.get_edges",
  "pyoccad.explore.ExploreSubshapes.get_faces",
  "pyoccad.explore.ExploreSubshapes.get_shells",
  "pyoccad.explore.ExploreSubshapes.get_solids",
  "pyoccad.explore.ExploreSubshapes.get_vertices",
  "pyoccad.measure.MeasureCurve.derivatives",
  "pyoccad.measure.MeasureCurve.dimension",
  "pyoccad.measure.MeasureCurve.fraction_length",
  "pyoccad.measure.MeasureCurve.length",
  "pyoccad.measure.MeasureCurve.position_from_relative_curvilinear_abs",
  "pyoccad.measure.MeasureCurve.unique_dimension",
  "pyoccad.measure.MeasureDirection.dimension",
  "pyoccad.measure.MeasureExtrema._get_extremum_index",
  "pyoccad.measure.MeasureExtrema.between_2_curves",
  "pyoccad.measure.MeasureExtrema.between_curve_and_surface",
  "pyoccad.measure.MeasureExtrema.between_point_and_curve",
  "pyoccad.measure.MeasureExtrema.between_point_and_surface",
  "pyoccad.measure.MeasurePoint.dimension",
  "pyoccad.measure.MeasurePoint.unique_dimension",
  "pyoccad.measure.MeasureSurface.area",
  "pyoccad.measure.MeasureSurface.perimeter",
  "pyoccad.transform.BooleanOperation.common",
  "pyoccad.transform.BooleanOperation.cut",
  "pyoccad.transform.BooleanOperation.cut_half_space",
  "pyoccad.transform.BooleanOperation.extrude_cut",
  "pyoccad.transform.BooleanOperation.fuse",
  "pyoccad.transform.BooleanOperation.fuse_with_fillet",
  "pyoccad.transform.BooleanOperation.section",
  "pyoccad.transform.BooleanOperation.split",
  "pyoccad.transform.Filling.from_profiles",
  "pyoccad.transform.Move.using_transformation",
  "pyoccad.transform.Rotate.around_x",
  "pyoccad.transform.Rotate.around_y",
  "pyoccad.transform.Rotate.around_z",
  "pyoccad.transform.Rotate.between_coord_systems",
  "pyoccad.transform.Scale.from_factor",
  "pyoccad.transform.Sweep.profile_along_path",
  "pyoccad.transform.Sweep.profiles_along_path",
  "pyoccad.transform.Translate.from_vector",
  "subshape_map",
  "sys",
  "sys.modules",
  "sys.modules.pop"
 ],
 "deps": {
  "GeomFill_NSections": [],
  "OCC": [],
  "TestClass": [],
  "_add_element_to_list": [],
  "abc": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "collections": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "create_common": [],
  "get_ax": [],
  "importlib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "inspect": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "math": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "move_point_and_tangent": [],
  "numpy": [
   "numpy/conda-forge/linux-64/numpy-1.9.3-py27_blas_openblashb06ca3d_7"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "pyoccad": [],
  "pythreejs": [
   "pythreejs/conda-forge/noarch/pythreejs-2.1.0-py_1"
  ],
  "scipy": [
   "scipy/conda-forge/linux-64/scipy-0.18.1-np111py34_blas_openblas_200"
  ],
  "subshape_map": [],
  "sys": [],
  "traitlets": [
   "traitlets/conda-forge/noarch/traitlets-5.0.3-py_0"
  ],
  "typing": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "unittest": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "uuid": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ]
 }
}